import "./globals.scss";
import { Poppins } from "next/font/google";
import { ViewTransitions } from "next-view-transitions";

const poppins = Poppins({ weight: ["400", "600"], subsets: ["latin"] });

export const metadata = {
  title: "My Form",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <ViewTransitions>{children}</ViewTransitions>
      </body>
    </html>
  );
}
